apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
        - image: <image_url>
          imagePullPolicy: Always
          name: api2
          ports:
            - name: api
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: api2
  labels:
    app: api2
    type: microservice
    release: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api
  selector:
    app: api2