apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
        - image: <image_url>
          imagePullPolicy: Always
          name: api2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api2
  labels:
    app: api2
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: api2